# Generated by Django 5.0.6 on 2024-06-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "dni",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("correo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "codigo",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("stock", models.IntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("numero_compra", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.cliente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="detalleCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("descripcion", models.CharField(max_length=100)),
                (
                    "compra",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.compra",
                    ),
                ),
            ],
        ),
    ]
