# Generated by Django 5.0.6 on 2024-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0002_categoria_producto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="descripcion",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
