# Generated by Django 5.0.6 on 2024-06-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0003_categoria_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="producto",
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="producto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.producto",
            ),
        ),
    ]
