# Generated by Django 5.0.6 on 2024-06-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0004_remove_compra_producto_detallecompra_producto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="total",
        ),
        migrations.AddField(
            model_name="categoria",
            name="identificador",
            field=models.CharField(default="ANOTHER", max_length=50),
        ),
        migrations.AddField(
            model_name="compra",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="cantidad",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="descripcion",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
