# Generated by Django 5.0.6 on 2024-06-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0004_remove_compra_producto_detallecompra_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="identificador",
            field=models.CharField(default="ANOTHER", max_length=6),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
