# Generated by Django 5.0.6 on 2024-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0005_categoria_identificador_alter_categoria_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
