# Generated by Django 5.0.6 on 2024-06-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0006_alter_producto_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="subtotal",
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="cantidad",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
