# Generated by Django 5.0.6 on 2024-06-19 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0007_remove_compra_cantidad_remove_compra_subtotal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallecompra",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="compra",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="subtotal",
        ),
        migrations.AddField(
            model_name="compra",
            name="cantidad",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="compra",
            name="producto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.producto",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
