# Generated by Django 5.0.6 on 2024-06-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0008_remove_detallecompra_cantidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="detalle_compra",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.detallecompra",
            ),
        ),
    ]
