# Generated by Django 5.0.6 on 2024-06-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0009_compra_detalle_compra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="detalle_compra",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="total",
        ),
        migrations.AddField(
            model_name="compra",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="compra",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.compra",
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="producto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.producto",
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
